version: "3.3"
services:
  otel-collector:
    image: otel/opentelemetry-collector:0.95.0
    command: ["--config=/etc/otel-collector-config.yaml", ""]
    volumes:
      - ./collector.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8889:8889" # Prometheus exporter metrics
      - "4317:4317" # OTLP gRPC receiver
      - "55679:55679"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    command: ["--config.file=/etc/prometheus/prometheus-config.yaml"]
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    ports:
      - "9090:9090"
